export const GET_PHOTOS_PENDING = 'GET_PHOTOS_PENDING';
export const GET_PHOTOS_REJECTED = 'GET_PHOTOS_REJECTED';
export const GET_PHOTOS_RESOLVED = 'GET_PHOTOS_RESOLVED';
export const GET_PHOTOS = 'GET_PHOTOS';
export const SET_PHOTO = 'SET_PHOTO';
