export const GET_PHOTOS_PENDING = 'GET_PHOTOS_PENDING';
export const GET_PHOTOS_REJECTED = 'GET_PHOTOS_REJECTED';
export const GET_PHOTOS_RESOLVED = 'GET_PHOTOS_RESOLVED';
export const GET_PHOTOS_PHONE_RESOLVED = 'GET_PHOTOS_PHONE_RESOLVED';
export const SET_INDEX_PHOTO_PHONE_LIST = 'SET_INDEX_PHOTO_PHONE_LIST';
export const GET_PHOTOS_API = 'GET_PHOTOS_API';
export const GET_PHOTOS_PHONE_GALLERY = 'GET_PHOTOS_PHONE_GALLERY';
export const SET_PHOTO = 'SET_PHOTO';
