export const GET_PHOTOS_PENDING = 'GET_PHOTOS_PENDING';
export const GET_PHOTOS_REJECTED = 'GET_PHOTOS_REJECTED';
export const GET_PHOTOS_RESOLVED = 'GET_PHOTOS_RESOLVED';
export const GET_PHOTOS_PHONE_RESOLVED = 'GET_PHOTOS_PHONE_RESOLVED';
export const SET_INDEX_PHOTO_PHONE_LIST = 'SET_INDEX_PHOTO_PHONE_LIST';
export const GET_PHOTOS = 'GET_PHOTOS';
export const SET_PHOTO = 'SET_PHOTO';
